server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    password: admin
    username: admin
  flyway:
    locations: classpath:/db/migration
payment:
  endpoint: https://dev.payment.com
